config/routes.rb
VisionBoard1::Application.routes.draw do
  resources :slideshows

  resources :pictures

  resources :musics

  resources :users

end

app/models/slideshow.rb
class Slideshow < ActiveRecord::Base
  attr_accessible :objective, :title, :user_id
end

app/controllers/slideshows_controller.rb
class SlideshowsController < ApplicationController
  # GET /slideshows
  # GET /slideshows.json
  def index
    @slideshows = Slideshow.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @slideshows }
    end
  end

  # GET /slideshows/1
  # GET /slideshows/1.json
  def show
    @slideshow = Slideshow.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @slideshow }
    end
  end

  # GET /slideshows/new
  # GET /slideshows/new.json
  def new
    @slideshow = Slideshow.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @slideshow }
    end
  end

  # GET /slideshows/1/edit
  def edit
    @slideshow = Slideshow.find(params[:id])
  end

  # POST /slideshows
  # POST /slideshows.json
  def create
    @slideshow = Slideshow.new(params[:slideshow])

    respond_to do |format|
      if @slideshow.save
        format.html { redirect_to @slideshow, notice: 'Slideshow was successfully created.' }
        format.json { render json: @slideshow, status: :created, location: @slideshow }
      else
        format.html { render action: "new" }
        format.json { render json: @slideshow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /slideshows/1
  # PUT /slideshows/1.json
  def update
    @slideshow = Slideshow.find(params[:id])

    respond_to do |format|
      if @slideshow.update_attributes(params[:slideshow])
        format.html { redirect_to @slideshow, notice: 'Slideshow was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @slideshow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slideshows/1
  # DELETE /slideshows/1.json
  def destroy
    @slideshow = Slideshow.find(params[:id])
    @slideshow.destroy

    respond_to do |format|
      format.html { redirect_to slideshows_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/slideshows_helper.rb
module SlideshowsHelper
end

app/views/slideshows/_form.html.erb
<%= form_for(@slideshow) do |f| %>
  <% if @slideshow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slideshow.errors.count, "error") %> prohibited this slideshow from being saved:</h2>

      <ul>
      <% @slideshow.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :objective %><br />
    <%= f.text_field :objective %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/slideshows/edit.html.erb
<h1>Editing slideshow</h1>

<%= render 'form' %>

<%= link_to 'Show', @slideshow %> |
<%= link_to 'Back', slideshows_path %>

app/views/slideshows/index.html.erb
<h1>Listing slideshows</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Objective</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @slideshows.each do |slideshow| %>
  <tr>
    <td><%= slideshow.title %></td>
    <td><%= slideshow.objective %></td>
    <td><%= slideshow.user_id %></td>
    <td><%= link_to 'Show', slideshow %></td>
    <td><%= link_to 'Edit', edit_slideshow_path(slideshow) %></td>
    <td><%= link_to 'Destroy', slideshow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Slideshow', new_slideshow_path %>

app/views/slideshows/new.html.erb
<h1>New slideshow</h1>

<%= render 'form' %>

<%= link_to 'Back', slideshows_path %>

app/views/slideshows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @slideshow.title %>
</p>

<p>
  <b>Objective:</b>
  <%= @slideshow.objective %>
</p>

<p>
  <b>User:</b>
  <%= @slideshow.user_id %>
</p>


<%= link_to 'Edit', edit_slideshow_path(@slideshow) %> |
<%= link_to 'Back', slideshows_path %>